# Site settings
author: Beverly Appleton
title: A journey to become and engineer 
header-img: img/home-bg.png
email: bfcain19@gmail.com
copyright_name: Beverly Appleton
description: > # this means to ignore newlines until "baseurl:"
  A journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bf_cain
github_username:  bfoxcain

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
